version: '3'
services:
  app-green:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app-green
    environment:
      - COLOR=green
      - PORT=8080
    ports:
      - "8082:8080"
