version: '3'
services:
  app-blue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app-blue
    environment:
      - COLOR=blue
      - PORT=8080
    ports:
      - "8081:8080"
